version: "3"
services:
  mongodb:
    container_name: recflix-db
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  recflix-backend:
    restart: always
    build:
      context: .
    expose:
      - "8080"
    depends_on:
      - mongodb
